// GENERATED by scripts/gen-image-variants.sh — do not edit by hand.
// Maps each static image to the widths actually on disk, largest last.
// Consumed by srcSet() in src/lib/images.ts.

export const imageVariants: Record<string, [number, string][]> = {
  "/shows/ark-news-daily.jpg": [[400, "/shows/ark-news-daily-400.jpg"], [800, "/shows/ark-news-daily-800.jpg"], [1200, "/shows/ark-news-daily.jpg"]],
  "/shows/call-me-back.jpg": [[400, "/shows/call-me-back-400.jpg"], [800, "/shows/call-me-back-800.jpg"], [1200, "/shows/call-me-back.jpg"]],
  "/shows/for-heavens-sake.jpg": [[400, "/shows/for-heavens-sake-400.jpg"], [800, "/shows/for-heavens-sake-800.jpg"], [1200, "/shows/for-heavens-sake.jpg"]],
  "/shows/whats-your-number.jpg": [[400, "/shows/whats-your-number-400.jpg"], [800, "/shows/whats-your-number-800.jpg"], [1200, "/shows/whats-your-number.jpg"]],
  "/hosts/amit-segal.jpg": [[400, "/hosts/amit-segal-400.jpg"], [793, "/hosts/amit-segal.jpg"]],
  "/hosts/dan-senor.jpg": [[400, "/hosts/dan-senor-400.jpg"], [800, "/hosts/dan-senor-800.jpg"], [1024, "/hosts/dan-senor.jpg"]],
  "/hosts/deborah-pardes.jpg": [[400, "/hosts/deborah-pardes-400.jpg"], [800, "/hosts/deborah-pardes-800.jpg"], [1200, "/hosts/deborah-pardes.jpg"]],
  "/hosts/donniel-hartman.jpg": [[400, "/hosts/donniel-hartman-400.jpg"], [800, "/hosts/donniel-hartman-800.jpg"], [980, "/hosts/donniel-hartman.jpg"]],
  "/hosts/nadav-eyal.jpg": [[400, "/hosts/nadav-eyal-400.jpg"], [800, "/hosts/nadav-eyal-800.jpg"], [1200, "/hosts/nadav-eyal.jpg"]],
  "/hosts/yael-wissner-levy.jpg": [[400, "/hosts/yael-wissner-levy-400.jpg"], [800, "/hosts/yael-wissner-levy-800.jpg"], [1200, "/hosts/yael-wissner-levy.jpg"]],
  "/hosts/yonatan-adiri.jpg": [[400, "/hosts/yonatan-adiri-400.jpg"], [500, "/hosts/yonatan-adiri.jpg"]],
  "/hosts/yossi-klein-halevi.jpg": [[400, "/hosts/yossi-klein-halevi-400.jpg"], [800, "/hosts/yossi-klein-halevi-800.jpg"], [1000, "/hosts/yossi-klein-halevi.jpg"]],
  "/inside-cmb.jpg": [[400, "/inside-cmb-400.jpg"], [800, "/inside-cmb-800.jpg"], [1200, "/inside-cmb.jpg"]],
};
