#!/usr/bin/env bash
# Generates responsive width variants for the static images in public/.
#
# Every <img> that renders one of these goes through `srcSet()` in
# src/lib/images.ts, so a phone showing a 163px cover fetches the 400w file
# instead of the full-size one.
#
# For each source, emits <name>-400.jpg and <name>-800.jpg alongside it, but
# only at widths *below* the source's own — never upscales. The original stays
# put and serves as the largest candidate. Re-runnable: it overwrites variants
# and skips sources that are already small.
#
# macOS only (uses sips). These are committed build artifacts, not a build step,
# so nothing on the deploy path depends on this running.
#
#   bash scripts/gen-image-variants.sh
set -euo pipefail

cd "$(dirname "$0")/.."
Q=80

# public/team/* is deliberately absent: those photos render nowhere (src/data/team.ts
# has no importers), so variants for them would be dead files. Add the glob back when
# an About team section actually ships — srcSet() already degrades to the plain `src`
# for any image the manifest doesn't know.
for f in public/shows/*.jpg public/hosts/*.jpg public/inside-cmb.jpg; do
  [ -e "$f" ] || continue
  case "$f" in *-400.jpg|*-800.jpg) continue ;; esac

  native=$(sips -g pixelWidth "$f" | awk '/pixelWidth/{print $2}')
  base="${f%.jpg}"

  for w in 400 800; do
    if [ "$native" -le "$w" ]; then
      # Source is already at or below this width — a variant would be an upscale.
      rm -f "${base}-${w}.jpg"
      continue
    fi
    # --resampleWidth, not -Z: -Z fits the *longest* side to $w, so a portrait
    # source would land narrower than $w while the manifest still advertised it
    # as "${w}w" — a srcset descriptor that lies. Every source happens to be
    # landscape or square today, which is exactly why this would go unnoticed.
    sips --resampleWidth "$w" -s format jpeg -s formatOptions $Q "$f" --out "${base}-${w}.jpg" >/dev/null 2>&1
  done
done

# Emit the manifest the app reads. A component can't stat the filesystem, and a
# srcset naming a file that doesn't exist is a 404 the browser may still pick —
# so the generator, which knows exactly what it wrote, records it.
MANIFEST=src/lib/image-variants.ts
{
  echo "// GENERATED by scripts/gen-image-variants.sh — do not edit by hand."
  echo "// Maps each static image to the widths actually on disk, largest last."
  echo "// Consumed by srcSet() in src/lib/images.ts."
  echo
  echo "export const imageVariants: Record<string, [number, string][]> = {"
  for f in public/shows/*.jpg public/hosts/*.jpg public/inside-cmb.jpg; do
    [ -e "$f" ] || continue
    case "$f" in *-400.jpg|*-800.jpg) continue ;; esac
    native=$(sips -g pixelWidth "$f" | awk '/pixelWidth/{print $2}')
    base="${f%.jpg}"
    url="${f#public}"
    entries=""
    for w in 400 800; do
      [ -e "${base}-${w}.jpg" ] && entries="${entries}[${w}, \"${base#public}-${w}.jpg\"], "
    done
    entries="${entries}[${native}, \"${url}\"]"
    echo "  \"${url}\": [${entries}],"
  done
  echo "};"
} > "$MANIFEST"

echo "Variants written. Totals:"
find public -name "*-400.jpg" | wc -l | xargs echo "  400w:"
find public -name "*-800.jpg" | wc -l | xargs echo "  800w:"
echo "Manifest: $MANIFEST"
