/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as IsraelVotesRouteImport } from './routes/israel-votes'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CircleSsoRouteImport } from './routes/circle-sso'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIndexRouteImport } from './routes/shows/index'
import { Route as PlusIndexRouteImport } from './routes/plus/index'
import { Route as NewslettersIndexRouteImport } from './routes/newsletters/index'
import { Route as HostsIndexRouteImport } from './routes/hosts/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ShowsWhatsYourNumberRouteImport } from './routes/shows/whats-your-number'
import { Route as ShowsInsideCallMeBackRouteImport } from './routes/shows/inside-call-me-back'
import { Route as ShowsForHeavensSakeRouteImport } from './routes/shows/for-heavens-sake'
import { Route as ShowsCallMeBackRouteImport } from './routes/shows/call-me-back'
import { Route as ShowsArkNewsDailyRouteImport } from './routes/shows/ark-news-daily'
import { Route as PlusRedeemRouteImport } from './routes/plus/redeem'
import { Route as PlusGiftRouteImport } from './routes/plus/gift'
import { Route as HostsSlugRouteImport } from './routes/hosts/$slug'
import { Route as AccountPodcastFeedRouteImport } from './routes/account/podcast-feed'
import { Route as AccountNewslettersRouteImport } from './routes/account/newsletters'
import { Route as AccountBillingRouteImport } from './routes/account/billing'
import { Route as NewslettersSlugIndexRouteImport } from './routes/newsletters/$slug/index'
import { Route as ShowsShowEpisodeRouteImport } from './routes/shows/$show/$episode'
import { Route as NewslettersSlugPostRouteImport } from './routes/newsletters/$slug/$post'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const IsraelVotesRoute = IsraelVotesRouteImport.update({
  id: '/israel-votes',
  path: '/israel-votes',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleSsoRoute = CircleSsoRouteImport.update({
  id: '/circle-sso',
  path: '/circle-sso',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusIndexRoute = PlusIndexRouteImport.update({
  id: '/plus/',
  path: '/plus/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersIndexRoute = NewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/hosts/',
  path: '/hosts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsWhatsYourNumberRoute = ShowsWhatsYourNumberRouteImport.update({
  id: '/shows/whats-your-number',
  path: '/shows/whats-your-number',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsInsideCallMeBackRoute = ShowsInsideCallMeBackRouteImport.update({
  id: '/shows/inside-call-me-back',
  path: '/shows/inside-call-me-back',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsForHeavensSakeRoute = ShowsForHeavensSakeRouteImport.update({
  id: '/shows/for-heavens-sake',
  path: '/shows/for-heavens-sake',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsCallMeBackRoute = ShowsCallMeBackRouteImport.update({
  id: '/shows/call-me-back',
  path: '/shows/call-me-back',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsArkNewsDailyRoute = ShowsArkNewsDailyRouteImport.update({
  id: '/shows/ark-news-daily',
  path: '/shows/ark-news-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusRedeemRoute = PlusRedeemRouteImport.update({
  id: '/plus/redeem',
  path: '/plus/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const PlusGiftRoute = PlusGiftRouteImport.update({
  id: '/plus/gift',
  path: '/plus/gift',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPodcastFeedRoute = AccountPodcastFeedRouteImport.update({
  id: '/account/podcast-feed',
  path: '/account/podcast-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNewslettersRoute = AccountNewslettersRouteImport.update({
  id: '/account/newsletters',
  path: '/account/newsletters',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountBillingRoute = AccountBillingRouteImport.update({
  id: '/account/billing',
  path: '/account/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersSlugIndexRoute = NewslettersSlugIndexRouteImport.update({
  id: '/newsletters/$slug/',
  path: '/newsletters/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowEpisodeRoute = ShowsShowEpisodeRouteImport.update({
  id: '/shows/$show/$episode',
  path: '/shows/$show/$episode',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersSlugPostRoute = NewslettersSlugPostRouteImport.update({
  id: '/newsletters/$slug/$post',
  path: '/newsletters/$slug/$post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/circle-sso': typeof CircleSsoRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/israel-votes': typeof IsraelVotesRoute
  '/logout': typeof LogoutRoute
  '/setup': typeof SetupRoute
  '/welcome': typeof WelcomeRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/newsletters': typeof AccountNewslettersRoute
  '/account/podcast-feed': typeof AccountPodcastFeedRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/plus/gift': typeof PlusGiftRoute
  '/plus/redeem': typeof PlusRedeemRoute
  '/shows/ark-news-daily': typeof ShowsArkNewsDailyRoute
  '/shows/call-me-back': typeof ShowsCallMeBackRoute
  '/shows/for-heavens-sake': typeof ShowsForHeavensSakeRoute
  '/shows/inside-call-me-back': typeof ShowsInsideCallMeBackRoute
  '/shows/whats-your-number': typeof ShowsWhatsYourNumberRoute
  '/account/': typeof AccountIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/newsletters/': typeof NewslettersIndexRoute
  '/plus/': typeof PlusIndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/newsletters/$slug/$post': typeof NewslettersSlugPostRoute
  '/shows/$show/$episode': typeof ShowsShowEpisodeRoute
  '/newsletters/$slug/': typeof NewslettersSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/circle-sso': typeof CircleSsoRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/israel-votes': typeof IsraelVotesRoute
  '/logout': typeof LogoutRoute
  '/setup': typeof SetupRoute
  '/welcome': typeof WelcomeRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/newsletters': typeof AccountNewslettersRoute
  '/account/podcast-feed': typeof AccountPodcastFeedRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/plus/gift': typeof PlusGiftRoute
  '/plus/redeem': typeof PlusRedeemRoute
  '/shows/ark-news-daily': typeof ShowsArkNewsDailyRoute
  '/shows/call-me-back': typeof ShowsCallMeBackRoute
  '/shows/for-heavens-sake': typeof ShowsForHeavensSakeRoute
  '/shows/inside-call-me-back': typeof ShowsInsideCallMeBackRoute
  '/shows/whats-your-number': typeof ShowsWhatsYourNumberRoute
  '/account': typeof AccountIndexRoute
  '/hosts': typeof HostsIndexRoute
  '/newsletters': typeof NewslettersIndexRoute
  '/plus': typeof PlusIndexRoute
  '/shows': typeof ShowsIndexRoute
  '/newsletters/$slug/$post': typeof NewslettersSlugPostRoute
  '/shows/$show/$episode': typeof ShowsShowEpisodeRoute
  '/newsletters/$slug': typeof NewslettersSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/circle-sso': typeof CircleSsoRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/israel-votes': typeof IsraelVotesRoute
  '/logout': typeof LogoutRoute
  '/setup': typeof SetupRoute
  '/welcome': typeof WelcomeRoute
  '/account/billing': typeof AccountBillingRoute
  '/account/newsletters': typeof AccountNewslettersRoute
  '/account/podcast-feed': typeof AccountPodcastFeedRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/plus/gift': typeof PlusGiftRoute
  '/plus/redeem': typeof PlusRedeemRoute
  '/shows/ark-news-daily': typeof ShowsArkNewsDailyRoute
  '/shows/call-me-back': typeof ShowsCallMeBackRoute
  '/shows/for-heavens-sake': typeof ShowsForHeavensSakeRoute
  '/shows/inside-call-me-back': typeof ShowsInsideCallMeBackRoute
  '/shows/whats-your-number': typeof ShowsWhatsYourNumberRoute
  '/account/': typeof AccountIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/newsletters/': typeof NewslettersIndexRoute
  '/plus/': typeof PlusIndexRoute
  '/shows/': typeof ShowsIndexRoute
  '/newsletters/$slug/$post': typeof NewslettersSlugPostRoute
  '/shows/$show/$episode': typeof ShowsShowEpisodeRoute
  '/newsletters/$slug/': typeof NewslettersSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/circle-sso'
    | '/community'
    | '/contact'
    | '/events'
    | '/israel-votes'
    | '/logout'
    | '/setup'
    | '/welcome'
    | '/account/billing'
    | '/account/newsletters'
    | '/account/podcast-feed'
    | '/hosts/$slug'
    | '/plus/gift'
    | '/plus/redeem'
    | '/shows/ark-news-daily'
    | '/shows/call-me-back'
    | '/shows/for-heavens-sake'
    | '/shows/inside-call-me-back'
    | '/shows/whats-your-number'
    | '/account/'
    | '/hosts/'
    | '/newsletters/'
    | '/plus/'
    | '/shows/'
    | '/newsletters/$slug/$post'
    | '/shows/$show/$episode'
    | '/newsletters/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/circle-sso'
    | '/community'
    | '/contact'
    | '/events'
    | '/israel-votes'
    | '/logout'
    | '/setup'
    | '/welcome'
    | '/account/billing'
    | '/account/newsletters'
    | '/account/podcast-feed'
    | '/hosts/$slug'
    | '/plus/gift'
    | '/plus/redeem'
    | '/shows/ark-news-daily'
    | '/shows/call-me-back'
    | '/shows/for-heavens-sake'
    | '/shows/inside-call-me-back'
    | '/shows/whats-your-number'
    | '/account'
    | '/hosts'
    | '/newsletters'
    | '/plus'
    | '/shows'
    | '/newsletters/$slug/$post'
    | '/shows/$show/$episode'
    | '/newsletters/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/circle-sso'
    | '/community'
    | '/contact'
    | '/events'
    | '/israel-votes'
    | '/logout'
    | '/setup'
    | '/welcome'
    | '/account/billing'
    | '/account/newsletters'
    | '/account/podcast-feed'
    | '/hosts/$slug'
    | '/plus/gift'
    | '/plus/redeem'
    | '/shows/ark-news-daily'
    | '/shows/call-me-back'
    | '/shows/for-heavens-sake'
    | '/shows/inside-call-me-back'
    | '/shows/whats-your-number'
    | '/account/'
    | '/hosts/'
    | '/newsletters/'
    | '/plus/'
    | '/shows/'
    | '/newsletters/$slug/$post'
    | '/shows/$show/$episode'
    | '/newsletters/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CircleSsoRoute: typeof CircleSsoRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  IsraelVotesRoute: typeof IsraelVotesRoute
  LogoutRoute: typeof LogoutRoute
  SetupRoute: typeof SetupRoute
  WelcomeRoute: typeof WelcomeRoute
  AccountBillingRoute: typeof AccountBillingRoute
  AccountNewslettersRoute: typeof AccountNewslettersRoute
  AccountPodcastFeedRoute: typeof AccountPodcastFeedRoute
  HostsSlugRoute: typeof HostsSlugRoute
  PlusGiftRoute: typeof PlusGiftRoute
  PlusRedeemRoute: typeof PlusRedeemRoute
  ShowsArkNewsDailyRoute: typeof ShowsArkNewsDailyRoute
  ShowsCallMeBackRoute: typeof ShowsCallMeBackRoute
  ShowsForHeavensSakeRoute: typeof ShowsForHeavensSakeRoute
  ShowsInsideCallMeBackRoute: typeof ShowsInsideCallMeBackRoute
  ShowsWhatsYourNumberRoute: typeof ShowsWhatsYourNumberRoute
  AccountIndexRoute: typeof AccountIndexRoute
  HostsIndexRoute: typeof HostsIndexRoute
  NewslettersIndexRoute: typeof NewslettersIndexRoute
  PlusIndexRoute: typeof PlusIndexRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
  NewslettersSlugPostRoute: typeof NewslettersSlugPostRoute
  ShowsShowEpisodeRoute: typeof ShowsShowEpisodeRoute
  NewslettersSlugIndexRoute: typeof NewslettersSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/israel-votes': {
      id: '/israel-votes'
      path: '/israel-votes'
      fullPath: '/israel-votes'
      preLoaderRoute: typeof IsraelVotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle-sso': {
      id: '/circle-sso'
      path: '/circle-sso'
      fullPath: '/circle-sso'
      preLoaderRoute: typeof CircleSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows/'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/': {
      id: '/plus/'
      path: '/plus'
      fullPath: '/plus/'
      preLoaderRoute: typeof PlusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/': {
      id: '/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters/'
      preLoaderRoute: typeof NewslettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/hosts'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/whats-your-number': {
      id: '/shows/whats-your-number'
      path: '/shows/whats-your-number'
      fullPath: '/shows/whats-your-number'
      preLoaderRoute: typeof ShowsWhatsYourNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/inside-call-me-back': {
      id: '/shows/inside-call-me-back'
      path: '/shows/inside-call-me-back'
      fullPath: '/shows/inside-call-me-back'
      preLoaderRoute: typeof ShowsInsideCallMeBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/for-heavens-sake': {
      id: '/shows/for-heavens-sake'
      path: '/shows/for-heavens-sake'
      fullPath: '/shows/for-heavens-sake'
      preLoaderRoute: typeof ShowsForHeavensSakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/call-me-back': {
      id: '/shows/call-me-back'
      path: '/shows/call-me-back'
      fullPath: '/shows/call-me-back'
      preLoaderRoute: typeof ShowsCallMeBackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/ark-news-daily': {
      id: '/shows/ark-news-daily'
      path: '/shows/ark-news-daily'
      fullPath: '/shows/ark-news-daily'
      preLoaderRoute: typeof ShowsArkNewsDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/redeem': {
      id: '/plus/redeem'
      path: '/plus/redeem'
      fullPath: '/plus/redeem'
      preLoaderRoute: typeof PlusRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plus/gift': {
      id: '/plus/gift'
      path: '/plus/gift'
      fullPath: '/plus/gift'
      preLoaderRoute: typeof PlusGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/podcast-feed': {
      id: '/account/podcast-feed'
      path: '/account/podcast-feed'
      fullPath: '/account/podcast-feed'
      preLoaderRoute: typeof AccountPodcastFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/newsletters': {
      id: '/account/newsletters'
      path: '/account/newsletters'
      fullPath: '/account/newsletters'
      preLoaderRoute: typeof AccountNewslettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/billing': {
      id: '/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AccountBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/$slug/': {
      id: '/newsletters/$slug/'
      path: '/newsletters/$slug'
      fullPath: '/newsletters/$slug/'
      preLoaderRoute: typeof NewslettersSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$show/$episode': {
      id: '/shows/$show/$episode'
      path: '/shows/$show/$episode'
      fullPath: '/shows/$show/$episode'
      preLoaderRoute: typeof ShowsShowEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/$slug/$post': {
      id: '/newsletters/$slug/$post'
      path: '/newsletters/$slug/$post'
      fullPath: '/newsletters/$slug/$post'
      preLoaderRoute: typeof NewslettersSlugPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CircleSsoRoute: CircleSsoRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  IsraelVotesRoute: IsraelVotesRoute,
  LogoutRoute: LogoutRoute,
  SetupRoute: SetupRoute,
  WelcomeRoute: WelcomeRoute,
  AccountBillingRoute: AccountBillingRoute,
  AccountNewslettersRoute: AccountNewslettersRoute,
  AccountPodcastFeedRoute: AccountPodcastFeedRoute,
  HostsSlugRoute: HostsSlugRoute,
  PlusGiftRoute: PlusGiftRoute,
  PlusRedeemRoute: PlusRedeemRoute,
  ShowsArkNewsDailyRoute: ShowsArkNewsDailyRoute,
  ShowsCallMeBackRoute: ShowsCallMeBackRoute,
  ShowsForHeavensSakeRoute: ShowsForHeavensSakeRoute,
  ShowsInsideCallMeBackRoute: ShowsInsideCallMeBackRoute,
  ShowsWhatsYourNumberRoute: ShowsWhatsYourNumberRoute,
  AccountIndexRoute: AccountIndexRoute,
  HostsIndexRoute: HostsIndexRoute,
  NewslettersIndexRoute: NewslettersIndexRoute,
  PlusIndexRoute: PlusIndexRoute,
  ShowsIndexRoute: ShowsIndexRoute,
  NewslettersSlugPostRoute: NewslettersSlugPostRoute,
  ShowsShowEpisodeRoute: ShowsShowEpisodeRoute,
  NewslettersSlugIndexRoute: NewslettersSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
